### ISSUE TITLE
simpleT dep

### ISSUE THREAD

**Issue by micnic** [karelsteinmetz/karma-jasmine-spec-runner-reporter#1]
Hi @karelsteinmetz,
I am going to release soon a new version of [simpleT](https://www.npmjs.com/package/simplet) (0.2.0), which is not backward compatible with the current 0.1.2 version, as I see you are using `^0.1.2` to define the dependency version value and it will get 0.2.0 as well when it's released, to avoid any undesired behavior I recommend you to change it to `~0.1.2` or just `0.1.2` as there will be no more releases in the 0.1.x branch.

**Comment by karelsteinmetz** [comment]
Hi, thanks. SimpleT was fixed to 0.1.\* and I will look at the 0.2.0 later.
